upstream garage_s3 {
    server   127.0.0.1:3900 weight=1;
}

upstream garage_web {
    server   127.0.0.1.244:3902 weight=1;
}

upstream garage_ui {
    server   127.0.0.1:3909 weight=1;
}


server {
    listen      443 ssl;
    server_name memos.s3-garage.techwork.cloud;
    
    include /usr/local/nginx/conf/conf.d/ssl.conf;
    include /usr/local/nginx/conf/conf.d/ssl.wildcard.s3-garage.techwork.cloud.conf;

    location / {
        access_log /usr/local/nginx/logs/s3_garage_access.log;
        error_log /usr/local/nginx/logs/s3_garage_error.log;
        proxy_pass http://garage_s3;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        Host $host;
        proxy_connect_timeout   180;
        proxy_send_timeout      180;
        proxy_read_timeout      180;
     #  proxy_buffer_size       128k;
     #  proxy_buffers           4 128k;
        proxy_buffer_size       10m;
        proxy_buffers           4 10m;

        proxy_busy_buffers_size 10m;
        proxy_temp_file_write_size 10m;
        add_header  Nginx-Cache "$upstream_cache_status";
        client_max_body_size 500M;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}

server {
    listen 80;
    server_name koala.techwork.cloud;
    return 301 https://koala.techwork.cloud$request_uri;
}

server {
    listen       443 ssl;
    server_name  koala.techwork.cloud;

    include /usr/local/nginx/conf/conf.d/ssl.conf;
    include /usr/local/nginx/conf/conf.d/ssl.wildcard.techwork.cloud.conf;

    location / {
        access_log /usr/local/nginx/logs/web_garage_access.log;
        error_log /usr/local/nginx/logs/web_garage_error.log;
        proxy_pass http://garage_web;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        Host $host;
        proxy_connect_timeout   180;
        proxy_send_timeout      180;
        proxy_read_timeout      180;
     #  proxy_buffer_size       128k;
     #  proxy_buffers           4 128k;
        proxy_buffer_size       10m;
        proxy_buffers           4 10m;

        proxy_busy_buffers_size 10m;
        proxy_temp_file_write_size 10m;
        add_header  Nginx-Cache "$upstream_cache_status";
        client_max_body_size 500M;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}

server {
    listen 80;
    server_name garage.techwork.cloud;
    return 301 https://garage.techwork.cloud$request_uri;
}

server {
    listen       443 ssl;
    server_name  garage.techwork.cloud;

    include /usr/local/nginx/conf/conf.d/ssl.conf;
    include /usr/local/nginx/conf/conf.d/ssl.wildcard.techwork.cloud.conf;

    location / {
        access_log /usr/local/nginx/logs/ui_garage_access.log;
        error_log /usr/local/nginx/logs/ui_garage_error.log;
        proxy_pass http://garage_ui;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        Host $host;
        proxy_connect_timeout   180;
        proxy_send_timeout      180;
        proxy_read_timeout      180;
        proxy_buffer_size       10m;
        proxy_buffers           4 10m;

        proxy_busy_buffers_size 10m;
        proxy_temp_file_write_size 10m;
        add_header  Nginx-Cache "$upstream_cache_status";
        client_max_body_size 500M;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}