server {
    listen       443 ssl;
    server_name  static.techwork.cloud;

    include /usr/local/nginx/conf/conf.d/ssl.conf;
    include /usr/local/nginx/conf/conf.d/ssl.wildcard.techwork.cloud.conf;

    location /assets {
        access_log /usr/local/nginx/logs/resources_access.log;
        error_log /usr/local/nginx/logs/resources_error.log;
        alias  /usr/local/nginx/resources/assets/;
    }

}